print ("---(name)---went to the---(place)---to get---(noun)---.")
print ("It was---(weather descriptor)---out.")
name = input("What is name? ")
place = input("What is place? ")
noun = input("What is noun? ")
weather = input("How's the weather? ")
print ("{} went to the {} to get {}." .format(name, place, noun))
print ("It was {} out." .format(weather))